/***************************************************************
* file: StartFrame.java
* author: Vincent Thai && Luis Lopez
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: program 1
* date last modified: 8/10/2016
*
* purpose: Main Program frame. Allows user to navigate through program.
*
****************************************************************/
package cs.pkg245;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Luis
 */
public class StartFrame extends javax.swing.JFrame {
       private BufferedImage img;
    /**
     * Creates new form TitleFrame
     */
    public StartFrame() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman, The Game");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jButton1.setText("Play");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                play(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 240, 100, 32);

        jButton2.setText("Highscores");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickHighscore(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 270, 100, 32);

        jButton3.setText("Credits");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToCredits(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 300, 100, 32);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Hangman");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, -40, 330, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs/pkg245/Pirate Ship.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 410, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickHighscore(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickHighscore
        // TODO add your handling code here:
        this.setVisible(false);
        HighScores high = null;
           try {
               high = new HighScores();
           } catch (IOException ex) {
               Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
        high.setLocationRelativeTo(null);
        high.setVisible(true);
        
    }//GEN-LAST:event_clickHighscore

    private void goToCredits(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToCredits
        // TODO add your handling code here:
        this.dispose();
        Credits credits = new Credits();
        credits.setLocationRelativeTo(null);
        credits.setVisible(true);
    }//GEN-LAST:event_goToCredits

    private void play(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_play
        this.dispose();
        PlayFrame p = new PlayFrame();
        p.setLocationRelativeTo(null);
        p.setBackground(Color.white);
        p.setVisible(true);
    }//GEN-LAST:event_play

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
